### ISSUE TITLE
EFB 群组的分享链接会自动失效

### ISSUE THREAD

**Issue by catbaron0** [shzxm/efb-install#1]
在博客的 [efb 讨论相关](https://blog.shzxm.com/2020/12/31/efb/) 一节中列出的群组分享链接是失效的。

事实上群组链接会每天失效，最新的有效链接会在第一个频道中更新。

**Comment by shzxm** [comment]
> 在博客的[efb讨论相关](https://blog.shzxm.com/2020/12/31/efb/)分段中列出的分组共享链接是失效的。
> 
> 实际上类别链接会每天失效，最新的有效链接会在第一个频道中更新。

已经修复.更改为github discussions

**Comment by shzxm** [comment]
啊.人生收到的第一条issue~爱你~
